### ISSUE TITLE
This deserves to be listed in the official Three.js examples list

### ISSUE THREAD

**Issue by chiaravalle** [Sean-Bradley/Bender#1]
Hello.
Because this is so good, I think you should ask the Three.js authors to include this demo in their external demos list.
I discovered this list by asking for demos here: https://github.com/mrdoob/three.js/issues/26771

Please, consider adding this demo then.

Regards, have a nice day =)

**Comment by Sean-Bradley** [comment]
Threejs is MIT, which means it promises nothing. It doesn't even have to be good. There are lots of people who develop libs for Threejs outside of the Threejs development lifecycle. I don't care if my Bender lib is part of the official Threejs collection. I don't really want the responsibility. I only wrote it quickly for fun. There is room for improvement. Its licensed MIT so no guarantees or warranties of being fit for any particular purpose.
What MIT also means, is that you yourself could, without restriction, create your own website, or series of blogs, highlighting the libs you like and discussing why.

**Comment by chiaravalle** [comment]
I see, and I understand.
